### DISCUSSION TITLE
action-automatic-releases always raise a "doesn't match any files"

### DISCUSSION THREAD

**Discussion by Mara-Li** [marvinpinto/actions#282] [Q&A]
As #236 I have this error.
In difference, I don't use any quote in my workflow. Also, I try to use full name and it doesn't work either.
Here is my workflow file : 
```yml
# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            WYSIWYG*
            folders*
```
