### ISSUE TITLE
Add the ability to send customized notification/chat messages

### ISSUE THREAD

**Issue by marvinpinto** [marvinpinto/actions#1]
For example:

``` yaml
- uses: "./packages/keybase-notifications/"
  with:
    message: "Hey there, world!"
    keybase_username: "${{ secrets.KeybaseUsername }}"
    keybase_paper_key: "${{ secrets.KeybasePaperKey }}"
    keybase_team_name: "${{ secrets.KeybaseTeamName }}"
    keybase_topic_name: "${{ secrets.KeybaseTopicName }}"
```

These would theoretically override any GitHub context, and be used to purely send out messages.
