### ISSUE TITLE
When 'automatic_release_tag:' is not latest, commit formatting errors occur

### ISSUE THREAD

**Issue by maggie0002** [marvinpinto/actions#113]
Thanks for this action, making my life much easier. 

Ran across a slight issue. When running the below with `automatic_release_tag: "develop" ` on a pre-release the formatting of the Commit details is lost. Here is an example: https://github.com/LearnersBlock/learners-block/releases

```
        name: Test process
        uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "develop"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip
```

When I run this with `automatic_release_tag: "latest"` it works fine. 

```
        name: Test process
        uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip
```

Using marvinpinto/action-automatic-releases@v1.1.1
