### ISSUE TITLE
Failed to find artifact file

### ISSUE THREAD

**Issue by pranjal-joshi** [marvinpinto/actions#146]
Hello, The action fails to find the uploaded artifact file to release.
I am attaching part of my `.yml` file below:
```
  ...
  Some Python Build and Test Job running on windows-latest which are working fine
  ...

    - name: Save EXE for a release
      uses: actions/upload-artifact@v2
      with:
        name: screenipy.exe
        path: .\dist\screenipy.exe

    - name: Release EXE
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        prerelease: true
        automatic_release_tag: "latest"
        files: |
          screenipy.exe
```
