### ISSUE TITLE
Can't use env vars on the tags/title

### ISSUE THREAD

**Issue by Macleykun** [marvinpinto/actions#178]
So i've been trying to do the following:
I want to extract from a commit the version and that version should be the tag and title.
I've tested for a while, and looking at this log, it seems i've achieved the above:
https://github.com/Macleykun/blobsaver/runs/2688604629?check_suite_focus=true

However, it seems that that marvinpinto/action-automatic-releases@latest doesn't understand that i'm giving a env var with a value:

```
Run echo $GITHUB_VERSION
  echo $GITHUB_VERSION
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_VERSION: v1.1.1
v1.1.1
9s
Run marvinpinto/action-automatic-releases@latest
Initializing the Automatic Releases action
Determining release tags
Retrieving commit history
Generating changelog
Generating release tag
  Attempting to create or update release tag "$GITHUB_VERSION"
  Could not create new tag "refs/tags/$GITHUB_VERSION" (Reference already exists) therefore updating existing tag "tags/$GITHUB_VERSION"
  Successfully created or updated the release tag "$GITHUB_VERSION"
```

The part of the workflow your interested in:
```
      - name: get version from commit
        run: echo "GITHUB_VERSION=$(echo ${{ github.event.commits[0].message }} | awk '{print $2}')" >> $GITHUB_ENV 
      - name: test the var
        run: echo $GITHUB_VERSION
      - name: release public builds
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: $GITHUB_VERSION
          prerelease: false
          files: "**"
```

I believe i'm doing it right on my side. However i would love to hear from others if this is indeed the case.
