### ISSUE TITLE
tagged-release assets

### ISSUE THREAD

**Issue by MioBlanco** [marvinpinto/actions#18]
Hi,
 your action is super simple and works well, but unfortunately the upload of files as release assets doesn't seem to work anymore.

**Comment by marvinpinto** [comment]
Hey there! How so? If you have a reproducible case (with debug logs) it would help to troubleshoot.

**Comment by MioBlanco** [comment]
Here's my testing Repo (https://github.com/isp-insoft-gmbh/TestRepo).
With the same files you should be able to reproduce it.
As you can see in the release workflow, i did everything as desribed and the release works fine when i push tags, but the assets don't come along the release

**Comment by marvinpinto** [comment]
Hey, which file were you expecting to show up in the release assets? If you are referring to `LICENSE.txt` per chance, I notice your worflow specifies:

```yaml
-  uses: "marvinpinto/action-automatic-releases@latest"
   with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      prerelease: false
      files: |
       LICENSE.txt
```

But I do not see a `LICENSE.txt` file in your repository (there is a `LICENSE` file there). Did you enable debug logs? (see the README). Debug logs should help troubleshoot these sort of issues.
