### ISSUE TITLE
`automatic_release_tag` is used instead of pushed git tag

### ISSUE THREAD

**Issue by radiantly** [marvinpinto/actions#189]
When a git tag is pushed, the action still uses the `automatic_release_tag` for the release if set. Relevant config:
```
uses: marvinpinto/action-automatic-releases@latest
with:
  repo_token: "${{ secrets.GITHUB_TOKEN }}"
  automatic_release_tag: "latest"
  prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
```
The full workflow file can be found [here](https://github.com/radiantly/Invisiwind/blob/ab36adbe4b97c3600126239579a5c6ceb910363b/.github/workflows/build.yml).

If this is unintended, I'm happy to open a PR fixing this issue.
