### ISSUE TITLE
Using Release branches with `automatic_release_tag` generates incorrect changelog

### ISSUE THREAD

**Issue by BickelLukas** [marvinpinto/actions#212]
We use release branches instead of tags. This means the trigger for our pipeline is: 
```yaml
on:
  push:
    branches: 
      - releases/*
```

Then we create the release with an `automatic_release_tag`: 
```yaml

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create Named Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: v${{ env.RELEASE_VERSION }}
          prerelease: false
```

This causes the changelog to not be generated from the last semver release but the last release of the same version (if exists, otherwise just the last commit). This would probably also be fixed if #16 is fixed.

I would be happy to submit a PR.
