### ISSUE TITLE
Glob patterns not working even though files exist, "Error: * doesn't match any files"

### ISSUE THREAD

**Issue by CybrNight** [marvinpinto/actions#395]
Hello, as with #270 and #236 I've been using this action for to create automatic releases for a project I am working on. The problem is that out of the blue the glob patterns have stopped working at random. I have tried trying to find the exact files I want and just FUCK IT and decided to try uploading all files in the working directory. At least then something would be uploaded, but I can't even tell it to get all files or a specific file. It always refuses to find the files I am looking for. Below is my current job.

```
prerelease:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    # This shows exactly that the files I need are downloaded properly
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - run: |
          ls *
[logs_138.zip](https://github.com/marvinpinto/actions/files/8032343/logs_138.zip)
[logs_138.zip](https://github.com/marvinpinto/actions/files/8032346/logs_138.zip)

          ls **/*.zip
          ls **/*.tar.gz

      - name: Update GitHub prerelease
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Latest Build"
          files: |
            *
```

Is there something REALLY stupid I'm missing or is this an on-going issue. It refuses to just package up the directory as is. I can worry about making it upload what I actually want later. Any ideas?

**Comment by vladislav06** [comment]
same issue

**Comment by acechef** [comment]
same issue!
My files selection:
```
files: |
  main.go
```

error output: main.go doesn't match any files

**Comment by zhfreal** [comment]
same issue!

**Comment by JaredPage** [comment]
I am experiencing the same issue here ! How can we include all artefacts that have been uploaded as part of the workflow ?

**Comment by Toby222** [comment]
Ditto

**Comment by LocalAccount1** [comment]
same issue?

**Comment by kw-stablekernel** [comment]
Version v1.2.1
Note: I've been able to solve issues on my side. Replacing `~` with explicit path `/home/runner`, i.e.:
Before:
```
- uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                files: |
                  ~/path/to/zip/file.zip
```
After:
```
- uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                files: |
                  /home/runner/path/to/zip/file.zip
```

Hope this helps someone!
