### ISSUE TITLE
Verbose mode to see the exact API calls that are made

### ISSUE THREAD

**Issue by probonopd** [marvinpinto/actions#40]
I would like to re-implement the following use of `action-automatic-releases` in Golang as part of a tool that does more than just upload to GitHub Releases.

For this it would be very useful to see the exact API calls `action-automatic-releases` makes (e..g, in curl syntax or something like that). 

Is there a way to see them?

```
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          Akira*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
```

Alternatively, can `action-automatic-releases` be somehow invoked from the command line, so that my Go-based tool can call it?
