### ISSUE TITLE
Feature request: custom header blocks based on commit prefixes/messages

### ISSUE THREAD

**Issue by jalavosus** [marvinpinto/actions#421]
I noticed that this action places commits which have "ci" somewhere in the commit message under a "Continuous Integration" header; it would be awesome if it were possible to add custom shorthands or commit prefixes to enable similar behavior for repo-specific changelogs. 

Config would look something like this:

```yaml
custom-commit-headers:
  tests: "Testing"
  build: "Build configuration"
  [... other keys/values ...]
```
