### ISSUE TITLE
automatic releases: tag being used instead of defined title

### ISSUE THREAD

**Issue by robotgryphon** [marvinpinto/actions#46]
Despite setting the `title` property under `with`, the action still seems to prefer simply bumping the pushed tag to a release instead.

Usage:
```
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v2
        with:
          name: libs
          path: buildfiles
        
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ github.event.release.tag_name }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            CHANGELOG.txt
            LICENSE.txt
            buildfiles/*
```

Example repository:
https://github.com/robotgryphon/mc-mod/blob/1.16.1/.github/workflows/gradle.yml
