### ISSUE TITLE
[action-automatic-releases] - Missing changelog between automatically created tags

### ISSUE THREAD

**Issue by proohit** [marvinpinto/actions#585]
Hey, in one of my projects ([accountingapp](https://github.com/proohit/accountingapp)), generating a changelog with the `action-automatic-releases` action only generates the last commit message as the release changelog. Anyone knows why that is?

I'm using the action like the following:
```yaml
steps:
  - uses: actions/checkout@master
  - name: Extract version
    id: extract_version
    uses: Saionaro/extract-package-version@v1.1.1
  - uses: "marvinpinto/action-automatic-releases@latest"
    with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      prerelease: false
      automatic_release_tag: ${{ steps.extract_version.outputs.version }}
      title: ${{ steps.extract_version.outputs.version }}
```
This should use the project version as title and tag. But for e.g. my [latest release (0.18.0)](https://github.com/proohit/accountingapp/releases/tag/0.18.0) and any other release, the changelog is just `Bump version 0.18.0`, which is the last commit message.

Thanks in advance!
